### ISSUE TITLE
Addresses endpoint uses v3 instead of v2

### ISSUE THREAD

**Issue by yamen** [JoshJancula/coinbase-advanced-node#11]
For example `client.rest.address.listAddresses` sends to `https://api.coinbase.com/api/v3/accounts/:id/addresses` instead of using the SIWC base url (https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-addresses).

Using the custom request works:

```javascript
client.rest.coinbaseRequest({
  baseURL: clientAdvanced.url.REST_SIWC,
  method: "get",
  url: `/accounts/${USDC_ACCOUNT}/addresses`,
});
```

I believe a similar thing happened for `transactions`, all the SIWC APIs under `/accounts` might be affected.

**Comment by JoshJancula** [comment]
I appreciate you bringing this to my attention. Resolved in version 2.1.0
