### ISSUE TITLE
 Conversion endpoints that support USD and USDC

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#13]
2023-NOV-27

Added conversion endpoints that support USD and USDC:

[Create Convert Quote](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_createconvertquote) creates quotes for converting currencies.
[Commit Convert Trade](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_commitconverttrade) commits a trade for converting currencies.
[Get Convert Trade](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_getconverttrade) returns a trade for converting currencies.

see: https://docs.cloud.coinbase.com/advanced-trade-api/docs/changelog

**Comment by JoshJancula** [comment]
Added support in [v3](https://github.com/JoshJancula/coinbase-advanced-node/pull/17)
