### ISSUE TITLE
Get UNIX Time

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#14]
2023-DEC-6

Added [Get UNIX Time](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_getunixtime) which allows users to get the current time from the Coinbase Advanced API.

see: https://docs.cloud.coinbase.com/advanced-trade-api/docs/changelog

**Comment by JoshJancula** [comment]
Are you asking for this endpoint to just be exposed from [TimeAPI](https://github.com/JoshJancula/coinbase-advanced-node/blob/main/src/time/TimeAPI.ts)? Or are you requesting this be utilized in favor of the SIWC time currently used [here]( https://github.com/JoshJancula/coinbase-advanced-node/blob/c03f3dfeff3e6dea63820aed1ed93e438983ce3d/src/Coinbase.ts#L71) to sign the request?

**Comment by JoshJancula** [comment]
The advance trade time requires auth so it cannot replace the legacy SIWC. This endpoint is now exposed in [v3](https://github.com/JoshJancula/coinbase-advanced-node/pull/17)
