### ISSUE TITLE
Support for Multiple Portfolios

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#15]
2023-DEC-11

Added support for [Multiple Portfolios](https://docs.cloud.coinbase.com/advanced-trade-api/docs/rest-api-portfolios):

Filtering by Retail Portfolio ID

Added new filtering parameter retail_portfolio_id to [List Orders](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_gethistoricalorders) and [Create order](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_postorder).
Endpoints

Added the following new /portfolios endpoints:

[List Portfolios](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_getportfolios)
GET /portfolios
[Create Portfolio](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_createportfolio)
POST /portfolios
[Move Portfolio Funds](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_moveportfoliofunds)
POST /portfolios/move_funds
[Get Portfolio Breakdown](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_getportfoliobreakdown)
GET /portfolios/{portfolio_uuid}
[Delete Portfolio](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_deleteportfolio)
DELETE /portfolios/{portfolio_uuid}
[Edit Portfolio](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_editportfolio)
PUT /portfolios/{portfolio_uuid}

see: https://docs.cloud.coinbase.com/advanced-trade-api/docs/changelog

**Comment by JoshJancula** [comment]
After reviewing the [docs](https://docs.cloud.coinbase.com/advanced-trade-api/docs/auth#authentication-schemes) it appears this feature is only supported when using the new Cloud API keys which cannot be used on SIWC APIs.

I am in favor of supporting this feature but support for Cloud API key authentication needs to be implemented first. Support to restrict usage of the SIWC APIs exposed by this library when using Cloud API keys will need to be added as well.

**Comment by JoshJancula** [comment]
Added support in [v3](https://github.com/JoshJancula/coinbase-advanced-node/pull/17)
