### ISSUE TITLE
doing a buy order

### ISSUE THREAD

**Issue by moblizeit** [JoshJancula/coinbase-advanced-node#21]
trying to do something like this in the node.js

 ```
const data:SIWCOrder = {

    accountId: '',
    amount: '5',
    agree_btc_amount_varies: true,
    currency: 'USD'
  }
  cloudClient.rest.buy.createBuy(data).then((resp:any) => {
    logger.info("Result of buy is:", resp)
  })
```

what would be the account id?

**Comment by JoshJancula** [comment]
From the docs [here](https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-buys#place-buy-order) 

`The account_id to place the buy order must be the account_id associated with the cryptocurrency you would like to buy. If you prefer to use a fiat account as the payment method, use the payment_method parameter.`

It is being used to provide the `account_id` here 
`POST https://api.coinbase.com/v2/accounts/:account_id/buys`

But you do bring up a good point that in my efforts to simplify the params I am proxying it in the request body and should be  stripping it out.

On a different note, from the same docs above...

`On November 30, the Sign in with Coinbase v2 [Buys](https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-buys) and [Sells](https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-sells) APIs are being deprecated.` 

I'd encourage you to use the `order` API's
