### ISSUE TITLE
Order REST api setup

### ISSUE THREAD

**Issue by moblizeit** [JoshJancula/coinbase-advanced-node#22]
I am trying to make a call to place a market order but struggling to initialize the payload for buy market order. below is how it looks currently

`
  const data:NewOrder = {
    client_order_id: '',
    product_id: 'BCH-USD',
    side:  OrderSide.BUY,
    order_configuration:  ???????
  }

  
  cloudClient.rest.order.placeOrder(data).then((resp:any) => {
    logger.info("Result of buy is:", resp)
  })
`

How do i initialize a market type order?

**Comment by JoshJancula** [comment]
Please see the doc references I have associated to every method. [Here](https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_postorder) is the official coinbase documentation for placing a market order. The `order_configuration` of your request should match a schema from there.
