### ISSUE TITLE
shared-request.ts - using params instead of pagination

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#23]
shared-request.ts - using `params` instead of `pagination` variable

`      params = formatPaginationIntoParams(params, true);
`
https://github.com/JoshJancula/coinbase-advanced-node/blob/83557148a1dc509c928d3c4220ba0ed55b0c1259/src/util/shared-request.ts#L35C43-L35C49

**Comment by JoshJancula** [comment]
thx, resolved in [v3.3.0](https://github.com/JoshJancula/coinbase-advanced-node/blob/main/CHANGELOG.md#330-2024-04-12)
