### ISSUE TITLE
GetOrder returning null

### ISSUE THREAD

**Issue by moblizeit** [JoshJancula/coinbase-advanced-node#26]
I am making call to getOrder after placing an order to see its status like below

`                const orderResp = await cloudClient.rest.order.getOrder(orderId)
`

It is returning null to me rather the order details. Looking at the documentation etc, I am not sure in what situation it will return null?

**Comment by JoshJancula** [comment]
If the order is not found (404 is returned) then this function will return null. You can find that in the code [here](https://github.com/JoshJancula/coinbase-advanced-node/blob/be91eca455346a164d1ae3029e2a1794cb2f7488/src/order/OrderAPI.ts#L401).

This is working just fine for me so I'd assume you are not providing a valid `order_id`
example:

```ts
  const myOrders = await client.rest.order.getOrders();
  console.info('my orders ', myOrders);
  const o = await client.rest.order.getOrder(myOrders.data[0].order_id);
  console.info(`order ${myOrders.data[0].order_id} details:`, o);
```

While all feedback is welcome, please only create issues that are actual code issues. This is the 3rd (non) issue you have opened that could have been resolved by looking at the docs or doing a tiny bit of investigation.

**Comment by moblizeit** [comment]
Well the order is is coming from placing a order and that is why it puzzles me. Here, is overall code where placeOrder is successful first.

` const resp:any = await cloudClient.rest.order.placeOrder(buyData)
  if(resp.success === true){
           const orderId = resp.order_id
                logger.info("Order id is:", orderId)
                const orderResp = await cloudClient.rest.order.getOrder(orderId)
                logger.log("Order buy status response is:", orderResp)
}
`

**Comment by JoshJancula** [comment]
@moblizeit those steps do not result in a null for me. I'm sorry you are experiencing issues, however it is not the purpose of this issue section to do your work for you. I'd advise you check the [scopes](https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/scopes) of the api keys you're using

code:
```ts
  const orderDetails = {
    client_order_id: crypto.randomUUID(),
    order_configuration: {
      limit_limit_gtc: {
        base_size: '5',
        limit_price: '0.30',
        post_only: false,
      },
    },
    product_id: 'ADA-USD',
    side: OrderSide.BUY,
  };
  console.info('order to place ', orderDetails);
  const newOrder = await client.rest.order.placeOrder(orderDetails);

  console.info('new order created: ', newOrder);
  const getOrder = await client.rest.order.getOrder(newOrder.order_id);
  console.info('response from getOrder ', getOrder);
```
response:
```bash
order to place  {
  client_order_id: '4d540abc-e100-4a74-9680-bea34172b93b',
  order_configuration: {
    limit_limit_gtc: { base_size: '5', limit_price: '0.30', post_only: false }
  },
  product_id: 'ADA-USD',
  side: 'BUY'
}
new order created:  {
  success: true,
  failure_reason: 'UNKNOWN_FAILURE_REASON',
  order_id: '1f8ddf74-8b75-4dee-b8be-0f3eba6925a5',
  success_response: {
    order_id: '1f8ddf74-8b75-4dee-b8be-0f3eba6925a5',
    product_id: 'ADA-USD',
    side: 'BUY',
    client_order_id: '4d540abc-e100-4a74-9680-bea34172b93b'
  },
  order_configuration: {
    limit_limit_gtc: { base_size: '5', limit_price: '0.30', post_only: false }
  }
}
response from getOrder  {
  order_id: '1f8ddf74-8b75-4dee-b8be-0f3eba6925a5',
  product_id: 'ADA-USD',
  user_id: 'xxxxx-xxxxx-xxxxxx-xxxxxxx-xxxxxxxxx',
  order_configuration: {
    limit_limit_gtc: { base_size: '5', limit_price: '0.3', post_only: false }
  },
  side: 'BUY',
  client_order_id: '4d540abc-e100-4a74-9680-bea34172b93b',
  status: 'OPEN',
  time_in_force: 'GOOD_UNTIL_CANCELLED',
  created_time: '2024-04-26T15:24:25.100298Z',
  completion_percentage: '0',
  filled_size: '0',
  average_filled_price: '0',
  fee: '',
  number_of_fills: '0',
  filled_value: '0',
  pending_cancel: false,
  size_in_quote: false,
  total_fees: '0',
  size_inclusive_of_fees: false,
  total_value_after_fees: '0',
  trigger_status: 'INVALID_ORDER_TYPE',
  order_type: 'LIMIT',
  reject_reason: 'REJECT_REASON_UNSPECIFIED',
  settled: false,
  product_type: 'SPOT',
  reject_message: '',
  cancel_message: '',
  order_placement_source: 'RETAIL_ADVANCED',
  outstanding_hold_amount: '1.515',
  is_liquidation: false,
  last_fill_time: null,
  edit_history: [],
  leverage: '',
  margin_type: 'UNKNOWN_MARGIN_TYPE',
  retail_portfolio_id: '026aa462-07a0-xxxx-xxxx-xxxxxxxxxxxxxxx'
}
```

**Comment by moblizeit** [comment]
Well i have seen this as a random behavior. it's not failing consistently. That's why i see it as an issue

**Comment by JoshJancula** [comment]
So now it works sometimes? If it 'works sometimes' I can't see how that would be a code issue from my end. Another guess at your issue is possibly some latency on coinbase servers, maybe try putting it in a 30 sec setTimeout to test that theory?

**Comment by moblizeit** [comment]
yes i can give that a try of checking order status little later
