### ISSUE TITLE
[Auth] Support CDP Keys

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#27]
Coinbase Advanced will stop support for Legacy API Keys on May 31, 2024 
`https://docs.cdp.coinbase.com/developer-platform/docs/cdp-keys/`

**Comment by JoshJancula** [comment]
Support for CDP auth was added in [v3.0.0](https://github.com/JoshJancula/coinbase-advanced-node/blob/main/CHANGELOG.md#new-features-2), however this library still refers to CDP auth by its former name of 'Cloud Auth'. Unless there is an issue with the functionality of cdp/cloud auth within this package I'm going to consider this to be already complete.

**Comment by romainbutteaud** [comment]
my bad!
