### ISSUE TITLE
[Advanced Trade] support for cursor in pagination

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#28]
For example `List Accounts` uses `cursor` for pagination and not `after`, `before` anymore
https://docs.cdp.coinbase.com/advanced-trade/reference/retailbrokerageapi_getaccounts/

**Comment by JoshJancula** [comment]
[see resolution here](https://github.com/JoshJancula/coinbase-advanced-node/issues/29#issuecomment-2185514497)
