### ISSUE TITLE
[SIWC] support for next_uri in pagination 

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#29]
For example `List Transactions` uses `next_uri` for pagination

https://docs.cdp.coinbase.com/sign-in-with-coinbase/docs/pagination/
https://docs.cdp.coinbase.com/sign-in-with-coinbase/docs/api-transactions/

**Comment by JoshJancula** [comment]
Resolved in [v4.0.0](https://github.com/JoshJancula/coinbase-advanced-node/blob/main/CHANGELOG.md#400-2024-06-24), particularly [this](https://github.com/joshjancula/coinbase-advanced-node/commit/f9de0832254e674061ec9206c72c3ecfcb389100) commit

To isolate per SIWC or Advance Trade specific types you'll want to do something like below although it it not necessary to do so with [UniversalPagination](https://github.com/JoshJancula/coinbase-advanced-node/blob/9d11a50f7855fb69a65c792fe56d85ab2e717433/src/payload/common.ts#L66).

```ts
  const data = await client.rest.account.listAccounts();
  const cursor = (data.pagination as AdvanceTradePagination).cursor;
```
