### ISSUE TITLE
CreateOrderResponse extra fields (order_id, failure_reason) 

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#31]
Coinbase doesn't return the `order_id` and `failure_reason` fields for the `CreateOrderResponse` anymore. 

https://github.com/JoshJancula/coinbase-advanced-node/blob/9d11a50f7855fb69a65c792fe56d85ab2e717433/src/order/OrderAPI.ts#L244

https://github.com/JoshJancula/coinbase-advanced-node/blob/9d11a50f7855fb69a65c792fe56d85ab2e717433/src/order/OrderAPI.ts#L242

**Comment by JoshJancula** [comment]
Coinbase deprecated these params [here](https://docs.cdp.coinbase.com/advanced-trade/docs/changelog#2024-jul-19), resolved in [v4.1.0](https://github.com/JoshJancula/coinbase-advanced-node/blob/main/CHANGELOG.md#410-2024-10-28)
