### ISSUE TITLE
2023-JUN-20 - Add Get Best Bid/Ask which returns the best bid/ask for all products.

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#5]
- 2023-JUN-20 - Add Get Best Bid/Ask which returns the best bid/ask for all products.
see: https://docs.cloud.coinbase.com/advanced-trade-api/docs/changelog

**Comment by JoshJancula** [comment]
Appreciate the feedback, addressed in [1.2.0](https://github.com/JoshJancula/coinbase-advanced-node/commit/ecd2fa69a32c23aa4550f221fab558766ca546e4)
