### ISSUE TITLE
2023-JUN-15 - Add Get Product Book which returns a list of bids and asks.

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#6]
- 2023-JUN-15 - Add Get Product Book which returns a list of bids and asks.
see: https://docs.cloud.coinbase.com/advanced-trade-api/docs/changelog

**Comment by JoshJancula** [comment]
Appreciate the feedback, addressed in [1.2.0](https://github.com/JoshJancula/coinbase-advanced-node/commit/ecd2fa69a32c23aa4550f221fab558766ca546e4)
