### ISSUE TITLE
Add best_bid, best_ask from Get Market Trades

### ISSUE THREAD

**Issue by romainbutteaud** [JoshJancula/coinbase-advanced-node#7]
on top of the `trades[]`, API also returns `best_bid` and `best_ask`
see: https://docs.cloud.coinbase.com/advanced-trade-api/reference/retailbrokerageapi_getmarkettrades

**Comment by JoshJancula** [comment]
Appreciate the feedback, addressed in [1.2.0](https://github.com/JoshJancula/coinbase-advanced-node/commit/ecd2fa69a32c23aa4550f221fab558766ca546e4)
